// Package public aggregates scrape results across many public HTTP+UDP trackers.
// Endpoint lists are curated from real-world deliverability tests — removing
// dead/slow trackers is cheaper than keeping them in the hot path.
package public

// HTTPEndpoints are tracker /scrape URLs that speak BEP 48 (bencoded multi-hash scrape).
// Each URL must end with the scrape path, not announce.
var HTTPEndpoints = []string{
	"https://tracker.renfei.net:8080/scrape",
	"https://tracker2.dler.org/scrape",
	"https://tracker.pmman.tech/scrape",
	"https://tracker.ghostchu-services.top/scrape",
	"https://shahidrazi.online/scrape",
	"https://http1.torrust-tracker-demo.com/scrape",
	"http://tracker.opentrackr.org:1337/scrape",
	"https://tracker.gbitt.info/scrape",
	"https://tracker.tamersunion.org/scrape",
	"https://t1.aag.moe:443/scrape",
	"https://tracker.loligirl.cn/scrape",
	"https://tr.burnabyhighstar.com/scrape",
	"https://tracker.bjut.jp:443/scrape",
	"http://tracker.files.fm:6969/scrape",
	"http://bt.okmp3.ru:2710/scrape",
	"http://ipv6.rer.lol:6969/scrape",
	// Batch 2 — ngosang/trackerslist 2025+ picks.
	"https://tracker.moeblog.cn:443/scrape",
	"https://tracker.lilacspecs.uk/scrape",
	"https://tracker.cloudit.top/scrape",
	"https://tracker-zhuqiy.dgj055.icu/scrape",
	"https://trackers.run/scrape",
	"http://tracker.beeimg.com:6969/scrape",
	"http://tracker.mywaifu.best:6969/scrape",
	"http://tracker.qu.ax:6969/scrape",
	"http://buny.uk:6969/scrape",
	"http://seeders-paradise.org:80/scrape",
	"http://tracker.openbittorrent.com:80/scrape",
	"http://tracker.tfile.co:80/scrape",
	"http://finbytes.org:80/scrape",
	"http://tracker.bt4g.com:2095/scrape",
	"http://bt1.xxxxbt.cc:6969/scrape",
}

// UDPEndpoints are tracker announce URLs that speak BEP 15 (UDP tracker protocol).
// Scrape is derived from the same host:port (UDP tracker protocol doesn't care about path).
var UDPEndpoints = []string{
	"udp://tracker.opentrackr.org:1337",
	"udp://tracker.torrent.eu.org:451",
	"udp://tracker.dler.org:6969",
	"udp://exodus.desync.com:6969",
	"udp://open.stealth.si:80",
	"udp://tracker.openbittorrent.com:6969",
	"udp://explodie.org:6969",
	"udp://tracker1.bt.moack.co.kr:80",
	"udp://tracker.theoks.net:6969",
	"udp://movies.zsw.ca:6969",
	"udp://retracker.lanta-net.ru:2710",
	"udp://open.demonii.com:1337",
	"udp://opentracker.i2p.rocks:6969",
	"udp://tracker.auctor.tv:6969",
	"udp://tracker.birkenwald.de:6969",
	"udp://tracker.bittor.pw:1337",
	"udp://tracker.dump.cl:6969",
	"udp://tracker.filemail.com:6969",
	"udp://tracker.moeking.me:6969",
	"udp://tracker.qu.ax:6969",
	"udp://tracker.srv00.com:6969",
	"udp://tracker.tamersunion.org:443",
	"udp://tracker.tiny-vps.com:6969",
	"udp://tracker-udp.gbitt.info:80",
	"udp://bt1.archive.org:6969",
	"udp://bt2.archive.org:6969",
	"udp://bubu.mapfactor.com:6969",
	"udp://epider.me:6969",
	"udp://ipv4announce.sktorrent.eu:6969",
	"udp://leet-tracker.moe:1337",
	"udp://new-line.net:6969",
	"udp://oh.fuuuuuk.com:6969",
	"udp://p2p.publictracker.xyz:6969",
	"udp://public.tracker.vraphim.com:6969",
	"udp://run.publictracker.xyz:6969",
	"udp://ttk2.nbaonlineservice.com:6969",
	"udp://z.mercax.com:53",
	"udp://isk.richardsw.club:6969",
	"udp://torrents.artixlinux.org:6969",
	"udp://wepzone.net:6969",
	"udp://tracker-1.gresille.org:80",
	"udp://tracker.gmi.gd:6969",
	"udp://tracker.kmzs123.cn:17272",
	"udp://tracker.skillindia.site:6969",
	"udp://ttk.publictracker.xyz:6969",
	"udp://d40969.acod.regrucolo.ru:6969",
	"udp://jutone.com:6969",
	"udp://ipv4.rer.lol:2710",
	// Batch 2 — 2025+ additions.
	"udp://tracker.openbittorrent.com:80",
	"udp://tracker.moeking.me:6969",
	"udp://udp.tracker.projectk.org:23333",
	"udp://tracker.0x7c0.com:6969",
	"udp://tracker.bitsearch.to:1337",
	"udp://tracker.torrust-demo.com:6969",
	"udp://tracker.skyts.net:6969",
	"udp://open.free-tracker.ga:6969",
	"udp://opentracker.io:6969",
	"udp://tracker.valete.tf:9999",
	"udp://openbittorrent.com:6969",
	"udp://tracker.mywaifu.best:6969",
	"udp://tracker.tryhackx.org:6969",
	"udp://free.publictracker.xyz:6969",
	"udp://1c.premierzal.ru:6969",
	"udp://martin-gebhardt.eu:25",
	"udp://6ahddutb1ucc3cp.ru:6969",
	"udp://4.tracker.devnak.win:6969",
	"udp://52.58.128.163:6969",
	"udp://discord.heihachi.pw:6969",
	"udp://hificode.in:6969",
	"udp://bittorrent-tracker.e-n-c-r-y-p-t.net:1337",
	"udp://extracker.dahrkael.net:6969",
	"udp://open.dstud.io:6969",
}

// MaxUDPHashesPerRequest caps how many 20-byte info_hashes we send in a single
// UDP scrape datagram. BEP 15 doesn't specify a limit, but practical MTU of 1500
// bytes allows up to 74 hashes (16-byte header + 74*20 = 1496). Stay conservative.
const MaxUDPHashesPerRequest = 70
